
use dadosgovbr;

create table dados_gov(
    Gestor VARCHAR(100), 
    Canal_de_Origem varchar(50), 
    Regiao varchar(2), 
    UF char(2), 
    Cidade varchar(50), 
    Sexo char(1),
    Faixa_Etaria varchar(30), 
    Ano_Abertura SMALLINT, 
    Mes_Abertura TINYINT, 
    Data_Abertura VARCHAR(20),
    Hora_Abertura varchar(20), 
    Data_Resposta varchar(20), 
    Hora_Resposta VARCHAR(20), 
    Data_Analise varchar(20),
    Hora_Analise varchar(20), 
    Data_Recusa varchar(20), 
    Hora_Recusa varchar(20), 
    Data_Finalizacao varchar(20),
    Hora_Finalizacao varchar(20), 
    Prazo_Resposta varchar(20), 
    Prazo_Analise_Gestor varchar(20),
    Tempo_Resposta SMALLINT, 
    Nome_Fantasia varchar(100), 
    Segmento_de_Mercado varchar(100), 
    Area varchar(50),
    Assunto varchar(100), 
    Grupo_Problema varchar(60), 
    Problema varchar(100), 
    Como_Comprou_Contratou varchar(50),
    Procurou_Empresa char(1), 
    Respondida char(1), 
    Situacao varchar(50), 
    Avaliacao_Reclamacao varchar(55),
    Nota_do_Consumidor TINYINT, 
    Analise_da_Recusa varchar(50), 
    Edicao_de_Conteudo char(1),
    Interacao_do_Gestor char(1), 
    Total TINYINT
) default charset=latin1 COLLATE latin1_general_ci;

